

class LenguageSyS:
    def __init__(self):
        self.list_traductions = {
            "es": {
                "error_installation": "Ha habido un error",
                "open_browser": "Abrir Navegador",
                "refresh": "Actualizar",
                "open_folder": "Abrir Folder",
                "total_mods_loaded": "Total Mods cargados",
                "limit_search": "Límite",
                'loaders': "Cargadores",
                "imgs": "Imagenes",
                'categories':'Categorias: ',
                "search": "Buscar",
                "home_pag": "Inicio",
                "next_pag": "Siguiente",
                "back_pag": "Atras",
                "init_mc": "Iniciando",
                "mc_path_create": "directorio creado",
                "profile_path_created": "archivo creado",
                "java_path_": "Ubicación de Java",
                "mc_path_": "Ubicación de Minecraft",
                "opacity": "Opacidad general",
                "need_restart": "Ciertas configuraciones realizadas necesitan de reinicio",
                "color_picker_text": "Color del tema",
                "version_not_installed": "No disponible",
                "settings_saved": "Configuraciones guardadas",
                "setting_saved_description": "Se han guardado las siguientes configuraciones",
                "session_closed": "Se ha cerrado tu sesión",
                "session_closed_description": "Has cerrado sesión como",
                "session_close": "Cerrar Sesión",
                "select_javaw": "Seleccionar",
                "select_img_wallpaper": "Seleccionar la imagen para cambiar el fondo de pantalla",
                "discord_rich": "Mostrar el launcher en Discord",
                "ram_usage": "Cambiar el uso de RAM en Minecraft",
                "wallpaper_save": "Cambiar la imagen de fondo del lanzador",
                "save_": "Guardar",
                "restore_": "Restaurar",
                "delete_all_": "Borrar Todo",
                "delete_all_confirmation_": "Borrar todos los datos almacenados",
                "invalid_version": "Versión no válida",
                "invalid_version_description": "es una versión válida",
                "installation_needed": "Necesita instalación",
                "installation_sucess": "Instalando versión...",
                "installation_sucess_description": "no se ha encontrado, se instalará",
                "file_not_found": "No se encontró el archivo especificado",
                "data_question_y": "Si",
                "data_elimination": "Eliminación de datos en curso",
                "data_elimination_sure": "¿Estás seguro de eliminar todos los datos?",
                "user_state_discord_conect": "Conectado",
                "user_state_discord_disconect": "No conectado",
                "user_state_discord_mainpage": "Página de inicio",
                "user_state_discord_playing": "Jugando Minecraft",
                "error_name_dialg_title": "Error en el nombre de usuario",
                "error_name_dialg_description": "El nombre de usuario proporcionado no es válido",
                "error_select_dialg_title": "Error tienes que elegir una versión válida",
                "error_select_dialg_description": "Elige una de las versiones mostradas en el apartado",
                "button_login": "Iniciar Sesión",
                "name_user": "Nombre de usuario",
                "name_user_hint": "Escribe tu nombre de usuario",
                "email_user": "Correo",
                "email_user_hint": "Escribe tu Correo",
                "java_recommended": "Es recomendado usar Java 1.17 para versiones recientes",
                "pass_user": "Contraseña",
                "pass_user_hint": "Escribe tu Contraseña",
                "versions_dropdown_label": "Elige la versión",
                "versions_dropdown": "Versiones",
                "sections_main": "Consola",
                "sections_profile": "Perfil",
                "sections_settings": "Ajustes",
                "play_button": "Jugar",
                "play_button_installing": "Instalando...",
                "lenguaje_dropdown": "Idioma",
                "lenguaje_dropdown_description": "Selecciona el idioma",
                "Resolution_perfil": "Resolución recomendada de la imagen 256x256 o 512x512"
            },
            "en": {
                "error_installation": "There has been an error",
                "open_browser": "Open Browser",
                "refresh": "Update",
                "open_folder": "Open Folder",
                "total_mods_loaded": "Total mods loaded",
                "limit_search": "Limit",
                'loaders': "Loader",
                "imgs": "Images",
                'categories':'Categories: ',
                "search": "Search",
                "home_pag": "Main",
                "next_pag": "Next",
                "back_pag": "Back",
                "init_mc": "Starting",
                "mc_path_create": "created directory",
                "profile_path_created": "file created",
                "java_path_": "Location of Java",
                "mc_path_": "Location of Minecraft",
                "opacity":"Overall opacity",
                "need_restart": "Certain settings made require a restart",
                "color_picker_text": "Theme color",
                "version_not_installed": "Not available",
                "settings_saved": "Saved settings",
                "setting_saved_description": "The following settings have been saved",
                "session_closed": "Your session has been closed",
                "session_closed_description": "You have logged out as",
                "session_close": "Log out",
                "select_javaw": "Select",
                "select_img_wallpaper": "Select the Image to change the Wallpaper",
                "discord_rich": "Display on discord launcher",
                "ram_usage": "Change usage RAM Minecraft",
                "wallpaper_save": "Change Background image launcher",
                "save_": "Save",
                "restore_": "Restore",
                "delete_all_": "Delete All",
                "delete_all_confirmation_": "Delete all stored data",
                "console_msg": "This is the console",
                "invalid_version": "Invalid Version",
                "invalid_version_description": "it is an invalid version",
                "installation_needed": "Need Installation",
                "installation_sucess": "Installing version...",
                "installation_sucess_description": "not found, will be installed",
                "file_not_found": "The specified file was not found",
                "data_question_y": "Yes",
                "data_elimination": "Data deletion in progress",
                "data_elimination_sure": "Are you sure you want to delete all data?",
                "user_state_discord_conect": "Connected",
                "user_state_discord_disconect": "Not connected",
                "user_state_discord_mainpage": "Home page",
                "user_state_discord_playing": "Playing Minecraft",
                "error_name_dialg_title": "Error in the username",
                "error_name_dialg_description": "The username provided is not valid",
                "error_select_dialg_title": "Error you have to choose a valid version",
                "error_select_dialg_description": "Choose one of the versions shown in the section",
                "button_login": "Sign in",
                "name_user": "Username",
                "name_user_hint": "Write your username",
                "email_user": "Email",
                "email_user_hint": "Write your email",
                "java_recommended": "It is recommended to use Java 1.17 for recent versions",
                "pass_user": "Password",
                "pass_user_hint": "Write your password",
                "versions_dropdown_label": "Select version",
                "versions_dropdown": "Versions",
                "sections_main": "Console",
                "sections_profile": "Profile",
                "sections_settings": "Settings",
                "play_button": "Play",
                "play_button_installing": "Installing...",
                "lenguaje_dropdown": "Language",
                "lenguaje_dropdown_description": "Select the language",
                "Resolution_perfil": "Recommended image resolution 256x256 or 512x512"
            }
        }
    
    def get(self):
        return self.list_traductions